name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - id: bait_setup
      name: Run Action
      uses: ./
    - name: Check output
      run: |
        echo "Action output is ${{ steps.bait_setup.outputs.version }}"
        bait version

        BAIT_VERSION=$(bait version)
        if [ "${{ steps.bait_setup.outputs.version }}" != "$BAIT_VERSION" ]; then
          echo "Output does not match expected value"
          exit 1
        fi
